## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [2]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [165]:
model1 = nn.Sequential(nn.Linear(2,3), nn.Sigmoid(), nn.Linear(3, 2), nn.Sigmoid())
model2 = nn.Sequential(nn.Linear(2,3), nn.Tanh(), nn.Linear(3, 2), nn.Sigmoid())
model3 = nn.Sequential(nn.Linear(2,3), nn.ReLU(), nn.Linear(3, 2), nn.Sigmoid())

model4 = nn.Sequential(nn.Linear(2,10), nn.Sigmoid(), nn.Linear(10, 2), nn.Sigmoid())
model5 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10, 2), nn.Sigmoid())
model6 = nn.Sequential(nn.Linear(2,10), nn.ReLU(), nn.Linear(10, 2), nn.Sigmoid())

model7 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2))
model8 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2), nn.Sigmoid())
model9 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2), nn.Tanh())

model = nn.Sequential(nn.Linear(2,3), nn.Tanh(), nn.Linear(3, 2), nn.Tanh())
model=model4
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=10, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=10, out_features=2, bias=True)
  (3): Sigmoid()
)


In [211]:
data_in = torch.tensor([[0.,0.], [0., 1.], [1., 0.], [1., 1.]]).float()
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [214]:
data_target = torch.tensor([[0.,0.], [1., 0.], [1., 0.], [0., 1.]]).float()
print(data_target)

tensor([[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])


In [167]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [168]:
num_epochs=1000
for epoch in range(num_epochs):
    optimizer.zero_grad()
    
    data_out = model(data_in)
    loss = criterion(data_out, data_target)
    
    loss.backward()
    optimizer.step()
    
    if(epoch+1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [100/1000], Loss: 0.5965
Epoch [200/1000], Loss: 0.5795
Epoch [300/1000], Loss: 0.5740
Epoch [400/1000], Loss: 0.5713
Epoch [500/1000], Loss: 0.5697
Epoch [600/1000], Loss: 0.5687
Epoch [700/1000], Loss: 0.5679
Epoch [800/1000], Loss: 0.5674
Epoch [900/1000], Loss: 0.5669
Epoch [1000/1000], Loss: 0.5666


In [215]:
model1 = nn.Sequential(nn.Linear(2,3), nn.Sigmoid(), nn.Linear(3, 2), nn.Sigmoid())
model2 = nn.Sequential(nn.Linear(2,3), nn.Tanh(), nn.Linear(3, 2), nn.Sigmoid())
model3 = nn.Sequential(nn.Linear(2,3), nn.ReLU(), nn.Linear(3, 2), nn.Sigmoid())

model4 = nn.Sequential(nn.Linear(2,10), nn.Sigmoid(), nn.Linear(10, 2), nn.Sigmoid())
model5 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10, 2), nn.Sigmoid())
model6 = nn.Sequential(nn.Linear(2,10), nn.ReLU(), nn.Linear(10, 2), nn.Sigmoid())

model7 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2))
model8 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2), nn.Sigmoid())
model9 = nn.Sequential(nn.Linear(2,10), nn.Tanh(), nn.Linear(10,10), nn.Tanh(), nn.Linear(10, 2), nn.Tanh())

model10 = nn.Sequential(nn.Linear(2,3), nn.Tanh(), nn.Linear(3, 2), nn.Tanh())


model = model1
print(model)



criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)



num_epochs=10000
for epoch in range(num_epochs):
    optimizer.zero_grad()
    
    data_out = model(data_in)
    loss = criterion(data_out, data_target)
    
    loss.backward()
    optimizer.step()
    
    if(epoch+1) % 1000 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")
        
        
        
        
with torch.no_grad():
    correct = 0
    total = 0
    
    data_out = model(data_in)
    predicted = torch.where(data_out < 0.5, 0., 1.)
    
    print(predicted)
    print(data_target)
    
    total += data_target.size(0)
    correct += torch.where((predicted == data_target).sum(1) == data_target.size(1), 1, 0).sum()

    accuracy = 100 * correct / total
    print(f"Validation Accuracy: {accuracy:.2f}%")
    
print(list(model.state_dict().values()))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=3, out_features=2, bias=True)
  (3): Sigmoid()
)
Epoch [1000/10000], Loss: 0.2148
Epoch [2000/10000], Loss: 0.2044
Epoch [3000/10000], Loss: 0.1857
Epoch [4000/10000], Loss: 0.1645
Epoch [5000/10000], Loss: 0.1475
Epoch [6000/10000], Loss: 0.1355
Epoch [7000/10000], Loss: 0.1243
Epoch [8000/10000], Loss: 0.1100
Epoch [9000/10000], Loss: 0.0911
Epoch [10000/10000], Loss: 0.0699
tensor([[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])
Validation Accuracy: 100.00%
[tensor([[-1.9818, -1.6564],
        [ 2.8434,  2.9709],
        [-2.8151, -2.8721]]), tensor([ 0.8426, -1.0325,  4.2563]), tensor([[-1.3465,  1.9564,  2.5433],
        [-2.9834,  3.4952, -4.9553]]), tensor([-2.7091, -0.4530])]
